// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-j8e61BC7dXDPkG8S4_IKmqpBxbUaWtI',
    appId: '1:498577113087:web:a3320e85779ad97597b1ca',
    messagingSenderId: '498577113087',
    projectId: 'labo001-77e8b',
    authDomain: 'labo001-77e8b.firebaseapp.com',
    storageBucket: 'labo001-77e8b.appspot.com',
    measurementId: 'G-G1CP1V635W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcd_Uh9GXe3T-q7aMf_YG2DAjHs2Kh_XU',
    appId: '1:498577113087:android:111ca5a6a369f8bb97b1ca',
    messagingSenderId: '498577113087',
    projectId: 'labo001-77e8b',
    storageBucket: 'labo001-77e8b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZCCAc7TRAHGb49ral__4ysw4pRDaxPxQ',
    appId: '1:498577113087:ios:463503798f718bb197b1ca',
    messagingSenderId: '498577113087',
    projectId: 'labo001-77e8b',
    storageBucket: 'labo001-77e8b.appspot.com',
    iosClientId: '498577113087-ik0noehf9p6j77lpd7jn1m6a912aipvd.apps.googleusercontent.com',
    iosBundleId: 'com.example.labo001',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZCCAc7TRAHGb49ral__4ysw4pRDaxPxQ',
    appId: '1:498577113087:ios:463503798f718bb197b1ca',
    messagingSenderId: '498577113087',
    projectId: 'labo001-77e8b',
    storageBucket: 'labo001-77e8b.appspot.com',
    iosClientId: '498577113087-ik0noehf9p6j77lpd7jn1m6a912aipvd.apps.googleusercontent.com',
    iosBundleId: 'com.example.labo001',
  );
}
